# Site settings
title: Alex L. L. Cancado
email: alxcancado@gmail.com.com
url: https://alxcancado.github.io
description: "I can create amazing things inside The Matrix using Swift, Wordpress, HTML5, JS, CSS, JQuery, Bootstrap, Phonegap, C# and Unity3D, Databases, Data Analysis and Data Visualization! It's an incredible world!"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 3498db #18bc9c #80B3FF #3498db
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Alex Lima Lopes Cancado
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/alxcancado
  #- title: facebook
  #  url:
  #- title: stack-overflow
  #  url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/alxcancado
  - title: github
    url: http://github.com/alxcancado

# Postal address (add as many lines as necessary)
address:
  - line: 7 Alta Pl.
  - line: Queenstown, 9300
  - line: New Zealand

# Credits content
credits: 'I can create amazing things inside The Matrix using Swift, Wordpress, HTML5, JS, CSS, JQuery, Bootstrap, Phonegap, C# and Unity3D, Databases, Data Analysis and Data Visualization! It's an incredible world!'

# Build settings
markdown: kramdown
permalink: pretty
